export const productTypeTranslations: { [key: string]: string } = {
  perishable: "Perecível",
  non_perishable: "Não Perecível",
  electronics: "Eletrônicos",
  t_shirt: "Camiseta",
  jacket: "Jaqueta",
  pants: "Calça",
  footwear: "Calçado",
  underwear: "Roupa Íntima",
  socks: "Meias",
  towel: "Toalha",
  sheet: "Lençol",
  mattress: "Colchão",
  blanket: "Cobertor",
  pencil: "Lápis",
  pen: "Caneta",
  eraser: "Borracha",
  backpack: "Mochila",
  toy: "Brinquedo",
  bag: "Bolsa",
  soap: "Sabonete",
  shampoo: "Shampoo",
  conditioner: "Condicionador",
  toothpaste: "Creme Dental",
  toothbrush: "Escova de Dentes",
  dental_floss: "Fio Dental",
  toilet_paper: "Papel Higiênico",
  deodorant: "Desodorante",
  detergent: "Detergente",
  laundry_cleaning_products: "Produtos de Limpeza para Roupas",
  general_cleaning_products: "Produtos de Limpeza Geral",
  hat: "Chapéu",
  gloves: "Luvas",
  scarf: "Cachecol",
  plate: "Prato",
  cutlery: "Talheres",
  glass: "Copo",
  pillow: "Travesseiro",
  pillowcase: "Fronha",
  other: "Outro",
};
