const productOptions = [
  {label : "Selecione",  value: ""},
  { label: "Perecível", value: "perishable" },
  { label: "Não Perecível", value: "non_perishable" },
  { label: "Eletrônicos", value: "electronics" },
  { label: "Camiseta", value: "t_shirt" },
  { label: "Jaqueta", value: "jacket" },
  { label: "Calça", value: "pants" },
  { label: "Calçado", value: "footwear" },
  { label: "Roupa Íntima", value: "underwear" },
  { label: "Meias", value: "socks" },
  { label: "Toalha", value: "towel" },
  { label: "Lençol", value: "sheet" },
  { label: "Colchão", value: "mattress" },
  { label: "Cobertor", value: "blanket" },
  { label: "Lápis", value: "pencil" },
  { label: "Caneta", value: "pen" },
  { label: "Borracha", value: "eraser" },
  { label: "Mochila", value: "backpack" },
  { label: "Brinquedo", value: "toy" },
  { label: "Bolsa", value: "bag" },
  { label: "Sabonete", value: "soap" },
  { label: "Shampoo", value: "shampoo" },
  { label: "Condicionador", value: "conditioner" },
  { label: "Creme Dental", value: "toothpaste" },
  { label: "Escova de Dentes", value: "toothbrush" },
  { label: "Fio Dental", value: "dental_floss" },
  { label: "Papel Higiênico", value: "toilet_paper" },
  { label: "Desodorante", value: "deodorant" },
  { label: "Detergente", value: "detergent" },
  { label: "Produtos de Limpeza para Roupas", value: "laundry_cleaning_products" },
  { label: "Produtos de Limpeza Geral", value: "general_cleaning_products" },
  { label: "Chapéu", value: "hat" },
  { label: "Luvas", value: "gloves" },
  { label: "Cachecol", value: "scarf" },
  { label: "Prato", value: "plate" },
  { label: "Talheres", value: "cutlery" },
  { label: "Copo", value: "glass" },
  { label: "Travesseiro", value: "pillow" },
  { label: "Fronha", value: "pillowcase" },
  { label: "Outro", value: "other" }
];

export default productOptions;
